import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AntdRegistry } from '@ant-design/nextjs-registry';
// import AuthProvider from './provider/AuthProvider';
import Header from './components/Header';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <AuthProvider> */}
        <AntdRegistry>
          <Header />
          {children}
        </AntdRegistry>
        {/* </AuthProvider> */}
      </body>
    </html>
  )
}
